### ISSUE TITLE
Add libmfx to FFMPEG

### ISSUE THREAD

**Issue by chriexpe** [MekayelAnik/ispyagentdvr-docker#11]
I was trying to get Agent to use QSV HW, but it would always return these two errors:
`SetupHardwareDecoding: Preferred decoder (AV_HWDEVICE_TYPE_QSV) does not support the profile. Using AV_HWDEVICE_TYPE_CUDA`
`FailHW: Couldn't create AV_HWDEVICE_TYPE_CUDA decoder. Using CPU instead.`
So I went ahead doing some troubleshooting and first I realized I needed to do GPU passthrough, as I use Unraid I installed SR-IOV plugin and added the Device `/dev/dri` at agent docker settings, but the error was still the same. 
But thanks to _**spornerama**_'s help I found that this FFMPEG build doesn't have _libmfx_, so that's why Agent can't do QSV HW.

**Comment by MekayelAnik** [comment]
What image have you used to deploy the container?

**Comment by chriexpe** [comment]
> @chriexpe Which docker image have you used to deploy the container?

Yours, but I used the template from _doitandbedone/ispyagentdvr_
![image](https://github.com/MekayelAnik/ispyagentdvr-docker/assets/16724821/50ae4a37-44bf-4a18-b496-df47997de93b)

**Comment by MekayelAnik** [comment]
Please use `mekayelanikispyagentdvr:gpu-hwaccel-latest`.
Before that please visit: [Dockerhub](https://hub.docker.com/r/mekayelanik/ispyagentdvr). Here u will have all tge needed instructions for the deployment. I would suggest Docker Compose for container deployment.
Also, I think u r a bit newb in docker. One suggestion will be, Always visit the Docker Hub or github Readme before deploying a container on your system.
Note: 
- QSV GPU HW Acceleration works on Intel 8th gen (2015 Broadswell) and later processors
- NVENC works on from GTX 1050ti and later
- AMD AMF supported Graphics Cards (Vega64 and later)

**Comment by chriexpe** [comment]
> One suggestion will be, Always visit the Docker Hub or github Readme before deploying a container on your system.

Thanks, I was relying only on your Github page, and as there wasn't any mention of HW Acceleration I thought it was baked-in on :latest or disabled.
My CPU is i5 12500, and I'm running the latest Unraid version 6.12.8 and i915 driver with SR-IOV plugin.
So I followed instructions from dockerhub and this is my _docker run_ (Unraid uses it by default):
```
docker run
  -d
  --name='Agent-DVR'
  --net='chriexpe'
  -e TZ="America/Sao_Paulo"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="Tower"
  -e HOST_CONTAINERNAME="Agent-DVR"
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:8090]'
  -l net.unraid.docker.icon='https://ispycontent.azureedge.net/img/ispy2.png'
  -p '8090:8090/tcp'
  -p '3478:3478/udp'
  -p '50000-50010:50000/udp'
  -v '/mnt/disk1/appdata/agentDVR/config':'/AgentDVR/Media/XML':'rw'
  -v '/mnt/nasa/nvr/':'/AgentDVR/Media/WebServerRoot/Media':'rw'
  -v '/mnt/disk1/appdata/agentDVR/commands':'/AgentDVR/Commands':'rw'
  --device='/dev/dri/renderD128'
  --device='/dev/dri/card0' 'mekayelanik/ispyagentdvr:gpu-hwaccel-latest'

7ec4f5f7b0ffa724eb1dd3584fa7b3f0807c29d5ac7c3ef6e43d7955e7edb2e8
```
Yet it will always say that does not support the profile, change to CUDA (?) and then software encoding.

**Comment by chriexpe** [comment]
One thing I didn't mention, I also have Jellyfin running on docker and always had issues with some movie formats, after realizing I needed to do GPU passthrough in order to Agent use hw accel, I also added --device /dev/dri to the settings and it was working flawleslly, so given that after doing the same process with AgentDVR and yet it didn't work, I thought the issue might be in FFMPEG, but I've been reading and libvpl (the one used by FFMPEG on :gpu-hwaccel-latest) is newer and better than libmfx, but different from the later one, this i915 driver doesn't support it?

**Comment by MekayelAnik** [comment]
@chriexpe 
Yes your CPU should work as it's newer than Broadswell.
Officially **Jellyfin FFMPEG** QSV supports **Brodswell** and newer intel GPUs & iGPUS. I don't see why it shouldn't.
Can u confirm that HWACCEL works on atleast one Video Format on your Unraid Jellyfin Server?
**If it runs on Jellyfin, then it MUST RUN on this container.**
I am roaming in the dark here, because I don't have devices to test the outcome. I don't have New Intel CPU, nor do a Nvidia GPU. So I am completely blind...
Hmm, Maybe I got it, I think the ispy uses the mfx explicitly..somehow. Maybe this is the reason **SeanT** replied that "mfx not enabled in FFMPEG"? It's a guess.
I can't enable the mfx in the FFMPEG as I don't control jellyfin-ffmpeg.
Even if I did, It would be pointless to digout a dead man (mfx is dead). Rather it will be wise to shift iSpy to use libvpl.

**Comment by ispysoftware** [comment]
I just pass the video stream codec ID into ffmpeg and it returns a list of hardware devices that can decode/ encode it. If it doesn't return anything then that usually means it's not supported. It's possible that on some platforms you need to specify some specific flags to get it to work - it's a bit of a mess in there. I don't specify vpl or mfx anywhere - that's on ffmpeg's side of things.
I'll see if i can find a computer here with QSV available on it and report back.

**Comment by MekayelAnik** [comment]
@ispysoftware Thank you

**Comment by chriexpe** [comment]
One update, VAAPI does work (from Agent logs):
```
SetupHardwareDecoding: Found decoder AV_HWDEVICE_TYPE_VAAPI
SetupHardwareDecoding: Opening AV_HWDEVICE_TYPE_VAAPI
SetupHardwareDecoding: Using hardware decoder: AV_HWDEVICE_TYPE_VAAPI
```
But QSV returns this (from docker console):
```
ffmpeg -hwaccel qsv -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -i 10_02_11-38-03-2024_378.mkv -f null - > /dev/null
ffmpeg version 6.0.1-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
[aac @ 0x55d5ea372100] channel element 1.11 is not allocated
Input #0, matroska,webm, from '10_02_11-38-03-2024_378.mkv':
  Metadata:
    ENCODER         : Lavf60.16.100
  Duration: 00:15:01.10, start: 0.000000, bitrate: 6331 kb/s
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 2560x1920, 20 fps, 20 tbr, 1k tbn
    Metadata:
      FLIP            : 0
      SPIN            : 0
      STARTTIME       : 638449763234154284
      TIMESTAMPOFFSET : 0
      DURATION        : 00:15:01.099000000
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
    Metadata:
      DURATION        : 00:15:01.004000000
libva info: VA-API version 1.20.0
libva info: Trying to open /usr/lib/jellyfin-ffmpeg/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_20
libva info: va_openDriver() returns 0
libva info: VA-API version 1.20.0
libva info: Trying to open /usr/lib/jellyfin-ffmpeg/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_20
libva info: va_openDriver() returns 0
libva info: VA-API version 1.20.0
libva info: Trying to open /usr/lib/jellyfin-ffmpeg/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_20
libva info: va_openDriver() returns 0
libva info: VA-API version 1.20.0
libva info: Trying to open /usr/lib/jellyfin-ffmpeg/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_20
libva info: va_openDriver() returns 0
libva info: VA-API version 1.20.0
libva info: Trying to open /usr/lib/jellyfin-ffmpeg/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_20
libva info: va_openDriver() returns 0
libva info: VA-API version 1.20.0
libva info: Trying to open /usr/lib/jellyfin-ffmpeg/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_20
libva info: va_openDriver() returns 0
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (h264_qsv) -> wrapped_avframe (native))
  Stream #0:1 -> #0:1 (aac (native) -> pcm_s16le (native))
Press [q] to stop, [?] for help
[aac @ 0x55d5ea3920c0] channel element 1.11 is not allocated
Error while decoding stream #0:1: Invalid data found when processing input
[aac @ 0x55d5ea3920c0] skip_data_stream_element: Input buffer exhausted before END element found
Error while decoding stream #0:1: Invalid data found when processing input
[aac @ 0x55d5ea3920c0] Multiple frames in a packet.
[aac @ 0x55d5ea3920c0] Input buffer exhausted before END element found
Error while decoding stream #0:1: Invalid data found when processing input
[h264_qsv @ 0x55d5ea392580] Failed to transfer data to output frame: -22.
Error while processing the decoded data for stream #0:0
Conversion failed!
```

**Comment by MekayelAnik** [comment]
@chriexpe this means that HWACCEL is Working with QSV, and FFMPEG is able to found the intel driver.so files.
QSV is a VAAPI implementation if I am not mistaking, maybe this is why ispy is senseing vaap decoder.
Pure VAAPI is used by AMD graphics.
So, I will say, it's working.

**Comment by MekayelAnik** [comment]
All the known GPU HARDWARE ACCELERATED Encoder/Decoder related issues till this date, have been solved in v5.3.3.0
Please use image equal or newer than `mekayelanik/ispyagentdvr:gpu-hwaccel-5.3.3.0`
Special shout out to **Sean** from **iSpy Software**

**Comment by chriexpe** [comment]
Thanks, too bad I still can't use QSV, it's that same error as before:

> Preferred decoder (AV_HWDEVICE_TYPE_QSV) does not support the profile. Using AV_HWDEVICE_TYPE_CUDA
> SetupHardwareDecoding: Setting preferred decoder to cuda
> SetupHardwareDecoding: Opening AV_HWDEVICE_TYPE_CUDA
> FailHW: Couldn't create AV_HWDEVICE_TYPE_CUDA decoder. Using CPU instead.

**Comment by MekayelAnik** [comment]
@chriexpe 
**Backup the Ispyagentdvr** From: Settings > Backup
Please pull the latest image `mekayelanik/ispyagentdvr:gpu-hwaccel-latest`
Stop & remove `ispyagentdvr` container then.
Remove the config directory of the AgentDVR container 

Then deploy the agentDVR container.
Extract the backup.
Restore everything from backup. [NOTE: Don't Delete the Backup]

After the deployment. 

Go to Each & every Camera settings :
i) General > Sourcer Type (Click on Blue button with 3 dots) > From drop-down select 'Advance' > Decoder (Select GPU from drop-down) > GPU Decoder (Select 'qsv' from drop-down)

ii) Recording > Encode (Select "Encode with Timestamp") > Advanced Settings > Codec (Select "qsv_hevc)

After that follow the logs.html and give the errors seen in the log.

Lets see what it shows.

**Comment by ispysoftware** [comment]
QSV doesn't support decoding all types of video formats - you might need to update your drivers or the video codec your camera is using might not be able to be decoded by QSV

**Comment by MekayelAnik** [comment]
@chriexpe if u don't provide adequate information, it will be considered that there is no mentionable problems.

**Comment by chriexpe** [comment]
> @chriexpe if u don't provide adequate information, it will be considered that there is no mentionable problem.

Sorry this is a whole new rabbit hole for me lol, but here is what you asked before:
As I'm using Unraid things is a bit different, so I removed container+data, removed appdata folder (where Commands and XML are located), and decided to use Docker Compose (from your DockerHub page) instead of a Template:
```
---
version: "3.9"
services:
  ispyagentdvr:
    image: mekayelanik/ispyagentdvr:gpu-hwaccel-latest
    container_name: ispyagentdvr
    environment:
      - PUID=1000
      - PGID=1000
      - WEBUI_PORT=8090
      - TZ=America/Sao_Paulo
    volumes:
      - /mnt/user/appdata/AgentDVR:/AgentDVR/Media/XML
      - /mnt/nasa/nvr:/AgentDVR/Media/WebServerRoot/Media
      - /mnt/user/appdata/AgentDVR:/AgentDVR/Commands
    ports:
      - 8090:8090
      - 3478:3478/udp
      - 50000-50010:50000-50010/udp
    devices:
     - /dev/dri/renderD128:/dev/dri/renderD128
     - /dev/dri/card0:/dev/dri/card0
    restart: unless-stopped
```
Then I decided to try just with one camera in case I misconfigured something, so I changed decoding to "qsv" and recording to encode with "hevc_qsv" on advanced tab, recorded a bit and then played it back (it also shows that same decode error as I also set it to use QSV).
(this happens after 19:36:06 PM timestamp)
[logs(6).txt](https://github.com/MekayelAnik/ispyagentdvr-docker/files/14737043/logs.6.txt)



> Also exac into the container and run:
> 
> ```
> vainfo --display drm --device /dev/dri/renderD128
> ffmpeg -v verbose -init_hw_device vaapi=va:/dev/dri/renderD128 -init_hw_device opencl@va
> ffmpeg -v debug -init_hw_device drm=dr:/dev/dri/renderD128 -init_hw_device vulkan@dr
> ```

This is what I got:

```
# vainfo --display drm --device /dev/dri/renderD128
ffmpeg -v verbose -init_hw_device vaapi=va:/dev/dri/renderD128 -init_hw_device opencl@va
ffmpeg -v debug -init_hw_device drm=dr:/dev/dri/renderD128 -init_hw_device vulkan@drTrying display: drm
libva info: VA-API version 1.21.0
libva info: Trying to open /usr/lib/jellyfin-ffmpeg/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_21
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.21 (libva 2.21.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 24.1.4 (a66b076)
vainfo: Supported profile and entrypoints
      VAProfileNone                   : VAEntrypointVideoProc
      VAProfileNone                   : VAEntrypointStats
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Simple            : VAEntrypointEncSlice
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointFEI
      VAProfileH264Main               : VAEntrypointEncSliceLP
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSlice
      VAProfileH264High               : VAEntrypointFEI
      VAProfileH264High               : VAEntrypointEncSliceLP
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Advanced            : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline: VAEntrypointFEI
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSliceLP
      VAProfileHEVCMain               : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointEncSlice
      VAProfileHEVCMain               : VAEntrypointFEI
      VAProfileHEVCMain               : VAEntrypointEncSliceLP
      VAProfileHEVCMain10             : VAEntrypointVLD
      VAProfileHEVCMain10             : VAEntrypointEncSlice
      VAProfileHEVCMain10             : VAEntrypointEncSliceLP
      VAProfileVP9Profile0            : VAEntrypointVLD
      VAProfileVP9Profile0            : VAEntrypointEncSliceLP
      VAProfileVP9Profile1            : VAEntrypointVLD
      VAProfileVP9Profile1            : VAEntrypointEncSliceLP
      VAProfileVP9Profile2            : VAEntrypointVLD
      VAProfileVP9Profile2            : VAEntrypointEncSliceLP
      VAProfileVP9Profile3            : VAEntrypointVLD
      VAProfileVP9Profile3            : VAEntrypointEncSliceLP
      VAProfileHEVCMain12             : VAEntrypointVLD
      VAProfileHEVCMain12             : VAEntrypointEncSlice
      VAProfileHEVCMain422_10         : VAEntrypointVLD
      VAProfileHEVCMain422_10         : VAEntrypointEncSlice
      VAProfileHEVCMain422_12         : VAEntrypointVLD
      VAProfileHEVCMain422_12         : VAEntrypointEncSlice
      VAProfileHEVCMain444            : VAEntrypointVLD
      VAProfileHEVCMain444            : VAEntrypointEncSliceLP
      VAProfileHEVCMain444_10         : VAEntrypointVLD
      VAProfileHEVCMain444_10         : VAEntrypointEncSliceLP
      VAProfileHEVCMain444_12         : VAEntrypointVLD
      VAProfileHEVCSccMain            : VAEntrypointVLD
      VAProfileHEVCSccMain            : VAEntrypointEncSliceLP
      VAProfileHEVCSccMain10          : VAEntrypointVLD
      VAProfileHEVCSccMain10          : VAEntrypointEncSliceLP
      VAProfileHEVCSccMain444         : VAEntrypointVLD
      VAProfileHEVCSccMain444         : VAEntrypointEncSliceLP
      VAProfileAV1Profile0            : VAEntrypointVLD
      VAProfileHEVCSccMain444_10      : VAEntrypointVLD
      VAProfileHEVCSccMain444_10      : VAEntrypointEncSliceLP
# ffmpeg version 6.0.1-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
[AVHWDeviceContext @ 0x5633c53ebd80] libva: VA-API version 1.21.0
[AVHWDeviceContext @ 0x5633c53ebd80] libva: Trying to open /usr/lib/jellyfin-ffmpeg/lib/dri/iHD_drv_video.so
[AVHWDeviceContext @ 0x5633c53ebd80] libva: Found init function __vaDriverInit_1_21
[AVHWDeviceContext @ 0x5633c53ebd80] libva: va_openDriver() returns 0
[AVHWDeviceContext @ 0x5633c53ebd80] Initialised VAAPI connection: version 1.21
[AVHWDeviceContext @ 0x5633c53ebd80] VAAPI driver: Intel iHD driver for Intel(R) Gen Graphics - 24.1.4 (a66b076).
[AVHWDeviceContext @ 0x5633c53ebd80] Driver not found in known nonstandard list, using standard behaviour.
[AVHWDeviceContext @ 0x5633c541e300] 0.0: Intel(R) OpenCL Graphics / Intel(R) UHD Graphics 770
[AVHWDeviceContext @ 0x5633c541e300] Intel QSV to OpenCL mapping function found (clCreateFromVA_APIMediaSurfaceINTEL).
[AVHWDeviceContext @ 0x5633c541e300] Intel QSV in OpenCL acquire function found (clEnqueueAcquireVA_APIMediaSurfacesINTEL).
[AVHWDeviceContext @ 0x5633c541e300] Intel QSV in OpenCL release function found (clEnqueueReleaseVA_APIMediaSurfacesINTEL).
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...
```

**Comment by chriexpe** [comment]
One thing I forgot to mention, I have both Intel GPU TOP and Intel Graphics SR-IOV plugins, and Jellyfin can use it just fine (with /dev/dri/ passthrough), actually I even played one raw recording from AgentDVR, this is the file info:
![jellyfin playing recording](https://github.com/MekayelAnik/ispyagentdvr-docker/assets/16724821/bcfee6ac-e0c4-409b-ac71-d2c7fe00c4b9)
And while playing it this was the GPU usage:
![jellyfin playing recording gpu](https://github.com/MekayelAnik/ispyagentdvr-docker/assets/16724821/58632b67-c171-4439-a623-bb5bb1cabc7a)
And these are the Jellyfin playback settings:
![jellyfin settings](https://github.com/MekayelAnik/ispyagentdvr-docker/assets/16724821/f344d71e-bc8a-4623-ab5e-377d93d81676)

And interestingly enough, for encoding, AgentDVR does use HW Encoding (even with QSV), but it just can't decode.
![image](https://github.com/MekayelAnik/ispyagentdvr-docker/assets/16724821/11c440c5-e285-434b-9aad-87d95167eec6)
btw I tested with only one camera set to use VAAPI decoding and the GPU usage was 1%

**Comment by ispysoftware** [comment]
https://drive.google.com/file/d/1ErO_nIPfcYZZqO050Bq7Cx1yCNqk1187/view?usp=sharing
should resolve issues with QSV decoding

**Comment by MekayelAnik** [comment]
@chriexpe please download and test the image: `mekayelanik/ispyagentdvr:gpu-hwaccel-5.3.5.0-test` and let us know if the Problem has been resolved.

I express my gratitude to @ispysoftware for this dedication and quick fix to almost any issues.

**Comment by chriexpe** [comment]
> QSV is different to every other H/W provider in ffmpeg for some reason - have to add a lot of "if QSV" code all over the place
> 
> https://drive.google.com/file/d/1ErO_nIPfcYZZqO050Bq7Cx1yCNqk1187/view?usp=sharing should resolve issues with QSV decoding

Thanks! And it sure did! Sorry I took a while to reply back as I was testing it but hey! No issues at all, tho if I push a little further QSV encoding on all cameras AgentDVR gets very unstable, where it freezes even if GPU and CPU usage is like 20% or less.
But CPU usage fell from 9% to only 4% now, and the issues with playback like that audio cut every 2 seconds was solved, actually scrubbing through the timeline the video loads instantly (tho with VAAPI it also worked).


> I express my gratitude to @ispysoftware for this dedication and quick fix to almost any issues.

And thank you @MekayelAnik for helping me too and making this testing way easier by releasing a dockerized version so quickly!

**Comment by MekayelAnik** [comment]
Dear @chriexpe ,
Alhamdulillah, your problem was solved & u found my work helpful.
I will consider this issue as FIXED.

U may leave further comments with details like: Number of Cameras in Your system, Current resolution that is used in Live View URL when u get the Agent to be Unstable by hitting it hard, which Brand of Camera & Method to link the camera to the Agent (ONVIF or RTSP etc.). Plus is that instability also occures when you use VAAPI to do the same kind of hard hitting?
Maybe there will be further refinement in the future Updates as I found @ispysoftware to be very enthusiastic about their work. They may get some que about the issue from your reply.
Also if u have OBX then, u may Screen capture the instability issues while high load as a relatively small video and what the log says when it gets nuts, then share that with us. I know it takes much time and effort, but if have liked the iSpy AgentDVR i would request u this favor for future improvements.

And I like to thank you for your time and effort for your patience & specifying the issues precisely with adequate information which takes very hard work and enthusiasm. Thank You.

Regards
