### ISSUE TITLE
No web interface since 2025-02-07

### ISSUE THREAD

**Issue by destroyed12** [MekayelAnik/ispyagentdvr-docker#31]
Hi, 
Since the update of 07 i can't access the web interface. 

When i look at the docker compose log i get : 

`Current AgentDVR Docker Image: 6.1.3.0

 If this Container is deployed on a Docker-Macvlan or Docker-IPvlan Network, then the IP Address of this AgentDVR container is: 172.20.0.2, Otherwise the AgentDVR IP is the IP of your HOST Server IP or localhost if you are accessing the WebUI from a Browser on the HOST Server.

 AgentDVR WebUI can be accessed on PORT: ﻿8090

 Therefore Most Probable AgentDVR WebUI Address: 172.20.0.2:﻿8090 or Your-HOST-Server-IP:﻿8090 or localhost:﻿8090

 iSpy Agent DVR is free to use locally for private use. You can add as many cameras as you like.

 SSL secured web access, SMS, Twitter, email alerts, mobile device access, cloud uploads, Virtual Reality and other services that use iSpy Agent DVR online platform require a subscription or an annual payment.

 If you desire to obtain a Subscription plan or want a Business License, please visit https://www.ispyconnect.com/pricing.aspx

The base image was updated on: Sun Feb  2 21:25:34 2025 : Bangladesh Time (UTC+06)

This docker image was built at: Sat Feb  8 21:27:31 +06 2025 : Bangladesh Time (UTC+06)

This Container was started on: Sun Feb  9 13:53:43 EST 2025

usermod: no changes

Failed to create secure directory (/root/.config/pulse): Permission denied`

I'm using your user compose with volumes set to work with my stuff  :

`services:
  ispyagentdvr:
    image: mekayelanik/ispyagentdvr:latest
    container_name: ispyagentdvr
    environment:
      - PUID=1000
      - PGID=1000
      - AGENTDVR_WEBUI_PORT=8090 
      - TZ=Asia/Dhaka
    volumes:
      - /path/to/config:/AgentDVR/Media/XML
      - /path/to/recordings:/AgentDVR/Media/WebServerRoot/Media
      - /path/to/commands:/AgentDVR/Commands
    ports:
      - 8090:8090
      - 3478:3478/udp
      - 50000-50100:50000-50100/udp
    restart: unless-stopped`

I'm using your stuff since at least 4 years thanks for your help

**Comment by MekayelAnik** [comment]
I usually deploy ispyagentdvr with MACVLAN, to give it it's own local IP.
But to verify that normal deployment is working, I have deployed the container using the above docker compose, which I believe is the default example docker compose. It works completely fine in my case. I can't reproduce your error.

Now that being said:

1. If you are updating directly from version `5.8.0.0` do the following:

- i) Redeploy the container using the image tag of `5.8.0.0` (or the last working version in your case) instead of `latest`
- ii) Backup the configs using the AgentDVR webui
- iii) Delete the container
- iv) Delete all config files from the **MAPPED HOST DIRECTORY** for **CONFIGS** (in your example docker compose that is `/path/to/config`)
- v) Deploy the container using `latest` tag
- vi) Restore the configs using AgentDVR WebUI.

Note: this is needed because the config file structure have been changed from XML to JSON. Also the database system has been updated. So old configs must be deleted.

2. If you are trying to open the WebUI from the host machine (on which the container is being deployed). Use:
`network_mode: "host" `
Note: Example be found [HERE](https://labex.io/tutorials/docker-how-to-use-docker-compose-with-host-network-configuration-394882)


**Bottomline:** The image is working without any sort of problem. I am testing this image continuously. Have my 24x7 Survaillance using this image. Couldn't reproduce you issue. I am closing this issue with this comment. If you face any further issues please leave comments here. Or even better, create a reddit post [HERE](https://www.reddit.com/r/ispyconnect/), with your **ORIGINAL DOCKER COMPOSE** and Error logs from `HOST-IP:8090/logs.html`. The large community will help you to understand what maybe the issue in your case. 

And last but not the least, always backup configs before updating docker containers.

Regards

**Comment by destroyed12** [comment]
Hi, 

it was strange i did need to MACVLAN an IP. 

I didn't change anything else and now it's back up. 

I still have the same error : `Failed to create secure directory (/root/.config/pulse): Permission denied`

But at least it's working 

Thank's for your help !

**Comment by MekayelAnik** [comment]
Glad to know your problem has been resolved. Keep in mind, you won't be able to access the WebUI from the host machine as MACVLAN is a virtually separated network from host network. And please make an backup of your AgentDVR from WebUI. It is necessary.

And the error you are getting is from `pulseaudio`. I also get that error and don't have any idea why this occurs. It's safe to ignore that error (at least to my knowledge).

Regrards
